### ISSUE TITLE
Possibly missing package 'im2mesh.data'

### ISSUE THREAD

**Issue by mkocabas** [autonomousvision/Occupancy-Networks#1]
Dear @LMescheder,

First, congrats for your CVPR paper and thanks for open sourcing the code.

When I try to run demo via `python generate.py configs/demo.yaml`, I am getting below error:
```
Traceback (most recent call last):
  File "generate.py", line 10, in <module>
    from im2mesh import config
  File "/home/Occupancy-Networks/im2mesh/config.py", line 3, in <module>
    from im2mesh import data
ImportError: cannot import name 'data'
```

Is there a missing package under `im2mesh`?

Best,

**Comment by LMescheder** [comment]
Hi @mkocabas,
thanks for reporting the issue. You are absolutely right. There were indeed some files missing, since there was a conflict in the `.gitignore`. Fixed in https://github.com/autonomousvision/Occupancy-Networks/commit/d93bc1fdb046238c9119aefbffc5d9d0d385d2bf.

**Comment by mkocabas** [comment]
Great, thanks!
